---
title: "Estimating Covid-19 Dynamics and Clinical Detection Rate using the SEIR N-Mixture Model"
author: "Ben Brintz"
institute: "Division of Epidemiology"
format: 
  revealjs:
    auto-animate-easing: ease-in-out
    auto-animate-unmatched: false
    auto-animate-duration: 2
    revealjs-plugins: 
    theme: white
    incremental: true
    slideNumber: false  # Slide numbers (optional)
    transition: fade   # Smooth slide transitions
    title-slide-background: "white" # Ensure title slide background matches your style
    css: custom.css    # Link to your custom CSS file
---

## The Covid-19 pandemic highlighted the challenge of imperfect detection in disease surveillance {auto-animate="true" .scrollable}

- Case reports undercount true infections due to asymptomatic cases and lack of access to testing
- Only the sickest got diagnosed with Covid early in the pandemic 
- "We must rely on data
from people who are sick enough to get themselves tested, which is a bit like trying to understand exercise
trends among average Americans by surveying the participants of a marathon"

## Various approaches have been developed to estimate clinical detection rates {auto-animate="true" .scrollable}

- **Back-calculation methods** estimate the number of infections from hospitalizations and deaths
- **Seroprevalence studies** estimate the proportion of the population that has been infected by testing for antibodies
- **SEIR models** estimate the number of infections from observed cases and the distribution of the incubation period

## Covid-19's incubation period requires an extension to the SIR compartment model {auto-animate="true" .scrollable}

- **SIR model** assumes that individuals
transition directly from susceptible to infectious
- **SEIR model** adds an exposed compartment to account for the incubation period
- **SEIR models** don't directly account for imperfect detection

## N-mixture models account for imperfect detection and have been applied to disease

- **N-mixture models** are traditionally used in ecology to estimate the abundance of a species from counts under the imperfect detection assumption
    - American Robin
    - Oregon Slender Salamander 
- Initial extensions of the **N-mixture model** allowed for survival and recruitment processes much like you would see in a compartment model
